Description: >
  Transactions Mgmt Kubernetes Cluster Stack.
  Backend Containers are deployed to this cluster as deployments.

Parameters:
  ClusterName:
    Description: EKS Cluster Name.
    Type: String
  EksClusterRole:
    Description: EKS Cluster Role ARN. To allow cluster to manage nodes aws users account.
    Type: String
  KubernetesVersion: 
    Description: Version of Kubernetes to run on cluster
    Type: String
    Default: 1.16

Resources:
  EksSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "{ClusterName}-Eks-SecurityGroup"
      GroupDescription: Allow access to our cluster controller
      VpcId:
        Fn::ImportValue: !Sub "${ClusterName}-VPCID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
  EKSCluster:
    Type: 'AWS::EKS::Cluster'
    Properties:
      Name: !Ref ClusterName
      Version: '1.16'
      RoleArn: !Ref EksClusterRole
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref EksSecGroup
        SubnetIds:
          - Fn::ImportValue: !Sub "${ClusterName}-PUB1-SN"
          - Fn::ImportValue: !Sub "${ClusterName}-PUB2-SN"
Outputs:
  EKSClusterArn:
    Value: !GetAtt EKSCluster.Arn
    Export:
      Name: !Sub ${ClusterName}-CLUSTER-ARN
  EKSClusterSecurityGroupId:
    Value: !GetAtt EKSCluster.ClusterSecurityGroupId
    Export:
      Name: !Sub ${ClusterName}-CLUSTER-SG
  EKSClusterEndpoint:
    Value: !GetAtt EKSCluster.Endpoint
    Export:
      Name: !Sub ${ClusterName}-CLUSTER-ENDPOINT
