version: '3.4'
services:
  postgres:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "transaction_mgmt_dev"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: