---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-{{ .DeploymentId }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: backend-{{ .DeploymentId }}
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend-{{ .DeploymentId }}
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - image: perfectmak/txmgmt:{{ .DeploymentId }}
        imagePullPolicy: Always
        name: backend-{{ .DeploymentId }}
        ports:
        - containerPort: 80
          name: http
        env:
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: server-secret
                key: DB_URL
          - name: PORT
            value: "80"
          - name: NODE_ENV
            value: production
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: service-{{ .DeploymentId }}
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: backend-{{ .DeploymentId }}
